# Generated by Django 3.0.1 on 2021-04-10 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('content', models.CharField(max_length=500, verbose_name='Project Content')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140, null=True, verbose_name='Image Title')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Image Description')),
                ('image', models.ImageField(upload_to='project_images')),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_project_images', to='projects.Project')),
            ],
            options={
                'verbose_name_plural': 'Project Images',
            },
        ),
    ]
