# Generated by Django 3.0.1 on 2021-04-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('message', models.CharField(max_length=250, verbose_name='Message')),
            ],
            options={
                'verbose_name_plural': 'Contact Messages',
            },
        ),
    ]
